/******************************************************************************************************
 SOFTWARE COPYRIGHT NOTICE:

 © [2013] Microchip Technology Inc. and its subsidiaries.
 You may use this software and any derivatives exclusively with Microchip products.

 THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED
 OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS,
 COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

 IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF
 MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT
 EXCEED THE AMOUNT OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

 MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE TERMS.
******************************************************************************************************/

#ifndef MAIN_H
#define MAIN_H

#ifdef __XC16__
#include <xc.h>
#endif


#define CH0_TRIS    &TRISD
#define CH0_LAT     &LATD
#define CH0_IO_BIT  2
#define CH0_AN_NUM  25

#define CH1_TRIS    &TRISD
#define CH1_LAT     &LATD
#define CH1_IO_BIT  3
#define CH1_AN_NUM  44

#define CH2_TRIS    &TRISD
#define CH2_LAT     &LATD
#define CH2_IO_BIT  12
#define CH2_AN_NUM  45


#define UI_BTN_LEFT       _RD2
#define UI_BTN_RIGHT      _RD12
#define UI_BTN_ENTER      _RD3 
#define UI_BTN_LEFT_TRIS  _TRISD2
#define UI_BTN_ENTER_TRIS _TRISD3
#include <stdint.h>
#endif //MAIN_H
